// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnjtnphtrvqtnqgxihmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuanRucGh0cnZxdG5xZ3hpaG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTIzOTYsImV4cCI6MjA2OTQyODM5Nn0.U-VrHCVF7J1KwW-Fdx0SZ3ck6M-Ub5f20hbBwZtMWvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});